apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false
secrets:
- name: {{ .Values.deployment.name }}-sa-token
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.name }}-sa-token
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.deployment.name }}
type: kubernetes.io/service-account-token